#!/bin/bash

if [ "$1" == "--help" ]; then
    echo " "
    echo   nomes 1.1 vig©© Ltda
    echo   nomes extensão nome
    echo   ex.:
    echo   nomes jpg \"buzios 2015\"
    echo " "
    echo   2015©
else
    X=1;
    for i in *$1 ; do
	mv  "$i" "$(printf %03d%s.%s ${X} "$2" $1 )"
	let X=$X+1
    done
fi
