#!/bin/bash

a=$(basename "$PWD")

if [ "$1" != "--help" ]; then
    mv "$1" S"$2"E"$3"\ -\ "$a"
else
    echo " "
    echo seriename 2.0 vig©© Ltda
    echo rename downloaded \(only illegaly\) TV series
    echo sintax:
    echo seriename [file] + [season number] + [episode number] or [--help for this help]
    echo " "
    echo 2015©
fi
	
