#!/bin/bash


stock=$1
buyin=$2
qtdde=$3

function Main(){
    if [ "$stock" == "" ];
    then
	echo " "
    else
	paragraph=$(w3m -no-cookie "https://www.google.com/search?q=$stock.SA" |grep "Brasil");

	
	a=( ${paragraph} )
	value=${a[1]}
	status=${a[2]}
	perct=${a[3]}

	if [ "$buyin" == "" ] || [ "$qtdde" == "" ];
	then
	    echo "$stock: $value $status $perct"
	else
	    gain=$(bc -l <<< "$qtdde*($value-$buyin)")
	    totalBuyed=$(bc -l <<< "$qtdde*$buyin")
	    perc=$(bc -l <<< "scale=2; 100*($totalBuyed+$gain)/$totalBuyed-100")
	    echo "$stock: $value $status $perct ¤ $gain ($perc%) "
	 fi
    fi
    
}

Main
